# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 高级Web课程@FDU
email: adwebfdu@126.com
description: > # this means to ignore newlines until "baseurl:"
  课程相关内容会被添加到这个repo里面.<br/>sharing is encouraged XD
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adwebfdu.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  adwebfdu

# Build settings
markdown: kramdown
